#!/usr/bin/python

# READ 1
fo = open("foo.txt", "r+")
str = fo.read();
fo.close()

# READ 2
fp = open('C:\WINDOWS\system32\drivers\etc\hosts', 'r')	
for line in fp.readlines():
	if " " in line:
		res = line.split(" ")[0]
fp.close()

# WRITE
fo = open("foo.txt", "wb")
fo.write( "Python is a great language.\nYeah its great!!\n");
fo.close()


#DESCRIPTION DE LA FONCTION OPEN()
r	Opens a file for reading only. The file pointer is placed at the beginning of the file. This is the default mode.
rb	Opens a file for reading only in binary format. The file pointer is placed at the beginning of the file. This is the default mode.
r+	Opens a file for both reading and writing. The file pointer will be at the beginning of the file.
rb+	Opens a file for both reading and writing in binary format. The file pointer will be at the beginning of the file.
w	Opens a file for writing only. Overwrites the file if the file exists. If the file does not exist, creates a new file for writing.
wb	Opens a file for writing only in binary format. Overwrites the file if the file exists. If the file does not exist, creates a new file for writing.
w+	Opens a file for both writing and reading. Overwrites the existing file if the file exists. If the file does not exist, creates a new file for reading and writing.
wb+	Opens a file for both writing and reading in binary format. Overwrites the existing file if the file exists. If the file does not exist, creates a new file for reading and writing.
a	Opens a file for appending. The file pointer is at the end of the file if the file exists. That is, the file is in the append mode. If the file does not exist, it creates a new file for writing.
ab	Opens a file for appending in binary format. The file pointer is at the end of the file if the file exists. That is, the file is in the append mode. If the file does not exist, it creates a new file for writing.
a+	Opens a file for both appending and reading. The file pointer is at the end of the file if the file exists. The file opens in the append mode. If the file does not exist, it creates a new file for reading and writing.
ab+	Opens a file for both appending and reading in binary format. The file pointer is at the end of the file if the file exists. The file opens in the append mode. If the file does not exist, it creates a new file for reading and writing.


# DELETE
import os
os.remove("text2.txt")


# RENAME
import os
os.rename( "test1.txt", "test2.txt" )


# MKDIR
import os
os.mkdir("test")


# CHANGE WORKING DIR
import os
# Changing a directory to "/home/newdir"
os.chdir("/home/newdir")


# GET WORKING DIR
import os
# This would give location of the current directory
os.getcwd()


# REMOVE DIR
import os
os.rmdir("/tmp/test")